In [1]:
import json

In [2]:
key = "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"

In [3]:
import requests

API_URL = "https://api-inference.huggingface.co/models/meta-llama/Prompt-Guard-86M"
headers = {"Authorization": f"Bearer {key}"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

output = query({
	"inputs": "I like you. I love you",
})

print(output)
print(output[0])
print()
for i in output[0]:
	print(i)

[[{'label': 'INJECTION', 'score': 0.9999321699142456}, {'label': 'BENIGN', 'score': 5.5546483054058626e-05}, {'label': 'JAILBREAK', 'score': 1.2239715942996554e-05}]]
[{'label': 'INJECTION', 'score': 0.9999321699142456}, {'label': 'BENIGN', 'score': 5.5546483054058626e-05}, {'label': 'JAILBREAK', 'score': 1.2239715942996554e-05}]

{'label': 'INJECTION', 'score': 0.9999321699142456}
{'label': 'BENIGN', 'score': 5.5546483054058626e-05}
{'label': 'JAILBREAK', 'score': 1.2239715942996554e-05}


In [4]:
# json.dumps(output, indent=4)

In [ ]:
from gradio_client import Client

client = Client("KingNish/OpenGPT-4o")
result = client.predict(
		user_prompt={"text":"who are you?","files":[]},
		api_name="/chat"
)
print(result)

In [14]:
import requests

# API_URL = "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-70B"
API_URL = "https://api-inference.huggingface.co/models/openai-community/gpt2"
headers = {"Authorization": f"Bearer {key}"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

output = query({
	"inputs": "create a simple python page",
})

print(output)

[{'generated_text': 'create a simple python page where you could easily zip a link to a web page I\'m most proud of, while still keeping things basic and clean.\n\nThis is where Crazy Password comes in handy. A Reddit user named "Fanys fran" managed to embed my code onto a plugin page about manhacks ledges to provide a place to spread my fun blog.\n\nThis kind of thing never fails.\n\n### Running Crazy Password\n\nIt\'s allowed to use cron like this but its command'}]


In [2]:
from transformers import GPT2Tokenizer, TFGPT2Model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = TFGPT2Model.from_pretrained('gpt2')
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

print(output)


All PyTorch model weights were used when initializing TFGPT2Model.

All the weights of TFGPT2Model were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2Model for predictions without further training.


TFBaseModelOutputWithPastAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 10, 768), dtype=float32, numpy=
array([[[ 0.16290486, -0.21657318, -0.1410281 , ..., -0.2618861 ,
         -0.08190866,  0.00923982],
        [ 0.46279654,  0.02483838, -0.07853661, ..., -0.08585841,
          0.5122233 , -0.39390516],
        [-0.06436804,  0.15511812, -0.63058436, ...,  0.24878454,
          0.36905366,  0.08326863],
        ...,
        [-0.55908066, -0.44902438, -1.45399   , ...,  0.16498925,
         -0.13022922, -0.37402695],
        [ 0.14001593, -0.38752776, -0.79156125, ..., -0.17796865,
          0.18236087,  0.21849138],
        [ 0.1720705 , -0.24204707, -0.11238763, ..., -0.1068425 ,
          0.12054715, -0.32129455]]], dtype=float32)>, past_key_values=(<tf.Tensor: shape=(2, 1, 12, 10, 64), dtype=float32, numpy=
array([[[[[-1.07186723e+00,  2.41698909e+00,  9.66034591e-01, ...,
           -4.78705823e-01, -3.31557006e-01,  1.79252338e+00],
          [-2.28969336e+00,  2.54